"""Initial Migration

Revision ID: 435148246c3d
Revises: b20116fa92f8
Create Date: 2019-02-28 12:59:19.184432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435148246c3d'
down_revision = 'b20116fa92f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('upvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'upvote')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'downvote')
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
